version: '2'

services:
  web-service:
    container_name: web-service
    build: .
    image: web-service:1.0
    ports:
      - "1323:1323"
    environment:
      - APP_NAME=github
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=123123
      - DB_NAME=go-flutter